from google colab import files #匯入套件

import pandas as pd

upload = files.upload() #開啟上傳介面並載入

data = pd.read_csv("剛剛上傳的檔案名稱")

In [17]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import os
os.chdir("/content/gdrive/MyDrive/112_2_LATIA/week3_0305/") # 切換目錄
!ls -l "/content/gdrive/MyDrive/112_2_LATIA/week3_0305/" # 列出目錄下的檔案
#!ls -l "自行填寫正確的路徑"

Mounted at /content/gdrive/
total 1454
-rw------- 1 root root   92484 Mar  5 06:27 112_student.csv
-rw------- 1 root root   21867 Mar 11 16:02 week3_demo.ipynb
-rw------- 1 root root 1374177 Mar 10 07:31 科展參賽證明書.pdf

In [18]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).

In [19]:
import pandas as pd

#csv_file = './112_student.csv'
csv_file = "./112_student.csv"

#columns = [
#    "學年度","學校代碼","學校名稱","日間∕進修別","等級別","總計","男生計",
#    "女生計","一年級男","一年級女","二年級男","二年級女","三年級男","三年級女",
#    "四年級男","四年級女","五年級男","五年級女","六年級男","六年級女",
#    "七年級男","七年級女","延修生男","延修生女","縣市名稱","體系別"
#]
df = pd.read_csv(csv_file) # 讀取csv檔案
print(df.head(), '\n')

#查看資料欄位資訊
print('\n', df.info(verbose=True, show_counts=True))

print('\n', df.isna().sum()) # 計算缺失數量並印出來

#查看資料的統計學資訊描述
print('\n', df.describe(include='all'))

   學年度  學校代碼    學校名稱 日間∕進修別   等級別    總計   男生計   女生計  一年級男  一年級女  ...  五年級男  \
0  112     1  國立政治大學    D 日  D 博士   921   517   404    86    69  ...    63
1  112     1  國立政治大學    D 日  M 碩士  4231  1835  2396   598   809  ...     2
2  112     1  國立政治大學    N 職  M 碩士  1903   938   965   262   304  ...    77
3  112     1  國立政治大學    D 日  B 學士  9763  3928  5835   906  1349  ...     0
4  112     2  國立清華大學    D 日  D 博士  1636  1131   505   206    93  ...   140

   五年級女  六年級男  六年級女  七年級男  七年級女  延修生男  延修生女    縣市名稱   體系別
0    52    68    37    66    50     0     0  30 臺北市  1 一般
1     1     1     0     0     0     0     0  30 臺北市  1 一般
2    57     0     0     0     0     0     0  30 臺北市  1 一般
3     0     0     0     0     0   316   499  30 臺北市  1 一般
4    60   110    50   115    56     0     0  18 新竹市  1 一般

[5 rows x 26 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學年度     764 non-null    int64
 1   學校代碼    764 non-null    int64
 2   學校名稱    764 non-null    object
 3   日間∕進修別  764 non-null    object
 4   等級別     764 non-null    object
 5   總計      764 non-null    int64
 6   男生計     764 non-null    int64
 7   女生計     764 non-null    int64
 8   一年級男    764 non-null    int64
 9   一年級女    764 non-null    int64
 10  二年級男    764 non-null    int64
 11  二年級女    764 non-null    int64
 12  三年級男    764 non-null    int64
 13  三年級女    764 non-null    int64
 14  四年級男    764 non-null    int64
 15  四年級女    764 non-null    int64
 16  五年級男    764 non-null    int64
 17  五年級女    764 non-null    int64
 18  六年級男    764 non-null    int64
 19  六年級女    764 non-null    int64
 20  七年級男    764 non-null    int64
 21  七年級女    764 non-null    int64
 22  延修生男    764 non-null    int64
 23  延修生女    764 non-null    int64
 24  縣市名稱    764 non-null    object
 25  體系別     764 non-null    object
dtypes: int64(21), object(5)
memory usage: 155.3+ KB

 None

 學年度       0
學校代碼      0
學校名稱      0
日間∕進修別    0
等級別       0
總計        0
男生計       0
女生計       0
一年級男      0
一年級女      0
二年級男      0
二年級女      0
三年級男      0
三年級女      0
四年級男      0
四年級女      0
五年級男      0
五年級女      0
六年級男      0
六年級女      0
七年級男      0
七年級女      0
延修生男      0
延修生女      0
縣市名稱      0
體系別       0
dtype: int64

           學年度         學校代碼    學校名稱 日間∕進修別   等級別            總計           男生計  \
count   764.0   764.000000     764    764   764    764.000000    764.000000
unique    NaN          NaN     145      4    10           NaN           NaN
top       NaN          NaN  弘光科技大學    D 日  M 碩士           NaN           NaN
freq      NaN          NaN      10    448   249           NaN           NaN
mean    112.0   756.200262     NaN    NaN   NaN   1433.022251    708.655759
std       0.0   504.152506     NaN    NaN   NaN   2633.932756   1385.170171
min     112.0     1.000000     NaN    NaN   NaN      1.000000      0.000000
25%     112.0    48.000000     NaN    NaN   NaN    103.750000     43.750000
50%     112.0  1029.000000     NaN    NaN   NaN    373.500000    180.000000
75%     112.0  1060.000000     NaN    NaN   NaN   1387.500000    590.500000
max     112.0  3002.000000     NaN    NaN   NaN  19466.000000  10885.000000

                 女生計         一年級男         一年級女  ...        五年級男        五年級女  \
count     764.000000   764.000000   764.000000  ...  764.000000  764.000000
unique           NaN          NaN          NaN  ...         NaN         NaN
top              NaN          NaN          NaN  ...         NaN         NaN
freq             NaN          NaN          NaN  ...         NaN         NaN
mean      724.366492   177.971204   173.545812  ...   11.871728   20.469895
std      1348.848241   349.047086   321.080379  ...   32.233288   81.117153
min         0.000000     0.000000     0.000000  ...    0.000000    0.000000
25%        50.000000     5.000000     4.000000  ...    0.000000    0.000000
50%       166.000000    41.000000    37.000000  ...    0.000000    0.000000
75%       718.500000   161.250000   188.250000  ...    6.000000    6.000000
max     10716.000000  2709.000000  2519.000000  ...  309.000000  897.000000

              六年級男        六年級女        七年級男        七年級女         延修生男  \
count   764.000000  764.000000  764.000000  764.000000   764.000000
unique         NaN         NaN         NaN         NaN          NaN
top            NaN         NaN         NaN         NaN          NaN
freq           NaN         NaN         NaN         NaN          NaN
mean      4.810209    3.615183    2.955497    1.742147    36.647906
std      19.818557   13.204157   17.768959    8.937397    98.370926
min       0.000000    0.000000    0.000000    0.000000     0.000000
25%       0.000000    0.000000    0.000000    0.000000     0.000000
50%       0.000000    0.000000    0.000000    0.000000     0.000000
75%       0.000000    0.000000    0.000000    0.000000    21.000000
max     179.000000  125.000000  312.000000  132.000000  1448.000000

               延修生女    縣市名稱   體系別
count    764.000000     764   764
unique          NaN      24     3
top             NaN  30 臺北市  2 技職
freq            NaN     120   468
mean      27.591623     NaN   NaN
std       74.731977     NaN   NaN
min        0.000000     NaN   NaN
25%        0.000000     NaN   NaN
50%        0.000000     NaN   NaN
75%       18.250000     NaN   NaN
max     1107.000000     NaN   NaN

[11 rows x 26 columns]

# 1.哪間大專院校有最多的學士生

step1: 取出想要查看的欄位，並印出此資料集共有多少筆紀錄 (len)

step2: 篩選等級別為"B 學士"的DataFrame，並印出有招生學士學制的學校數量

step3: 依據"總計"從大到小排序並印出結果 (sort_values, by, ascending)

In [20]:
# 請在"填空"處，輸入所需要的指令或參數

df1 = df[['等級別','總計','學校名稱']] # 取出想要觀看的欄位
print("本資料集共有", len(df1) , "筆紀錄")

df1_1 = df1[df1['等級別'] == 'B 學士']
print("有招生學士學制的學校數量為", len(df1_1) , "\n")

df1_1_sorted = df1_1.sort_values(by='總計', ascending=False)
print("112學年度在籍的學士生最多人數之學校為", df1_1_sorted.head(1)["學校名稱"].values)

本資料集共有 764 筆紀錄
有招生學士學制的學校數量為 97

112學年度在籍的學士生最多人數之學校為 ['淡江大學']

# 2. 國立？所；私立？所

step1: 建立空字串 (lsit=[])

step2: 建立for迴圈，配合if else條件，取出國立與私立

step3: 新增「公私立」column在DataFrame中 (df['公私立'])

step4: 篩選掉重複的學校代碼資料 (drop_duplicates)

step5: 計算公立與私立學校的筆數，並印出結果 (value_counts)

In [21]:
type_list = [] # 建立空字串

for i in df['學校名稱']:
    if ('國立' in i) or ('市立' in i):
        type_list.append('公立')
    else:
        type_list.append('私立')

df['公私立'] = type_list # 將 Dataframe 新增「公私立」column

df2 = df.drop_duplicates(subset=['學校代碼'])
count = df2['公私立'].value_counts()

print(df2)
print(f"本資料集共收集了 {len(df2)} 所學校，其中公立：{count['公立']} 所；私立：{count['私立']} 所。")

     學年度  學校代碼        學校名稱 日間∕進修別   等級別    總計   男生計   女生計  一年級男  一年級女  ...  \
0    112     1      國立政治大學    D 日  D 博士   921   517   404    86    69  ...
4    112     2      國立清華大學    D 日  D 博士  1636  1131   505   206    93  ...
9    112     3      國立臺灣大學    D 日  D 博士  3654  2454  1200   431   215  ...
13   112     4    國立臺灣師範大學    D 日  D 博士  1337   630   707   106   127  ...
17   112     5      國立成功大學    D 日  D 博士  1888  1228   660   219   136  ...
..   ...   ...         ...    ...   ...   ...   ...   ...   ...   ...  ...
753  112  1289  育英醫護管理專科學校    D 日  5 五專  1833   200  1633    39   343  ...
754  112  1291  聖母醫護管理專科學校    D 日  2 二專     2     2     0     0     0  ...
757  112  1292  新生醫護管理專科學校    N 修  2 二專    79    12    67     7    37  ...
759  112  1293  崇仁醫護管理專科學校    D 日  5 五專  3017   460  2557   112   515  ...
760  112  3002      臺北市立大學    D 日  D 博士   208    94   114    17    11  ...

     五年級女  六年級男  六年級女  七年級男  七年級女  延修生男  延修生女    縣市名稱   體系別  公私立
0      52    68    37    66    50     0     0  30 臺北市  1 一般   公立
4      60   110    50   115    56     0     0  18 新竹市  1 一般   公立
9     128   179   106   312   132     0     0  30 臺北市  1 一般   公立
13     83    59    85    87    89     0     0  30 臺北市  3 師範   公立
17     84   107    57   110    48     0     0  21 臺南市  1 一般   公立
..    ...   ...   ...   ...   ...   ...   ...     ...   ...  ...
753   276     0     0     0     0    13    77  50 高雄市  2 技職   私立
754     0     0     0     0     0     2     0  02 宜蘭縣  2 技職   私立
757     0     0     0     0     0     0     1  03 桃園市  2 技職   私立
759   529     0     0     0     0    19    45  10 嘉義縣  2 技職   私立
760    14     6     9    16    25     0     0  30 臺北市  1 一般   公立

[145 rows x 27 columns]
本資料集共收集了 145 所學校，其中公立：47 所；私立：98 所。

# 3. 各等級別學制共有？所

step1: 篩選掉重複的學校名稱與等級別 (drop_duplicates, subset)

step2: 計算出等級別的筆數 (value_counts)

step3: 建立等級別的字串，並找出其類別 (unique)

step4: 使用for迴圈，依序列出所有等級別學制的學校數量 (count)

In [22]:
df3 = df.drop_duplicates(subset=['學校名稱',"等級別"])
count = df3['等級別'].value_counts()
degree_list = list(df['等級別'].unique())

print(f"本資料集總共收集了 {len(set(df['學校名稱']))} 所學校，各等級學制當中：")
for degree in degree_list:
    print(f"一共有{count[degree]} 所學校， 有招收{degree}。")

本資料集總共收集了 145 所學校，各等級學制當中：
一共有84 所學校， 有招收D 博士。
一共有130 所學校， 有招收M 碩士。
一共有67 所學校， 有招收B 學士。
一共有1 所學校， 有招收X 4+X。
一共有71 所學校， 有招收C 二技。
一共有66 所學校， 有招收B 四技。
一共有46 所學校， 有招收5 五專。
一共有2 所學校， 有招收5 七年。
一共有46 所學校， 有招收2 二專。
一共有1 所學校， 有招收C 二年制。

# 4. 各縣市分別有？所，位於新北市的大專院校總共有幾所

# 5. 北中南東區分別有？所

都市及區域發展統計彙編 - 國發會 https://www.ndc.gov.tw/nc_77_4402

北部區域：包括臺北市、新北市、基隆市、新竹市、桃園市、新竹縣及宜蘭縣。

中部區域：包括臺中市、苗栗縣、彰化縣、南投縣及雲林縣。

南部區域：包括高雄市、臺南市、嘉義市、嘉義縣、屏東縣及澎湖縣。

東部區域：包括花蓮縣及臺東縣。

福建省：包括金門縣與連江縣。

# 6. 各體系別分別有？所

# 7. 國立/私立與男女比
請問國立大學與私立大學在學男生女生比例為何? 延修生男生女生比例為何?

# 8. 國立大學在學生男女比

 # 9. 每校平均最多與最少人的體系

# 10. 將新增的欄位寫入並儲存成新的CSV檔案，並命名為112_students_tf.csv

新增的欄位有"公私立"，"縣市名"，"區域"

# Q1.臺灣師範大學男生人數

In [34]:
df10 = df[['等級別','男生計','學校名稱']] # 取出想要觀看的欄位
print("本資料集共有", len(df10) , "筆紀錄")

df10_1 = df10[df10['學校名稱'] == '國立臺灣師範大學']

print("國立臺灣師範大學的男生人數:", df10_1['男生計'].sum())

本資料集共有 764 筆紀錄
國立臺灣師範大學的男生人數: 7034

#  Q2.台大學生女生總人數

In [36]:
df11 = df[['女生計','學校名稱']] # 取出想要觀看的欄位
print("本資料集共有", len(df11) , "筆紀錄")

df11_1 = df11[df11['學校名稱'] == '國立臺灣大學']

print("台大學生女生總人數:", df11_1['女生計'].sum())

本資料集共有 764 筆紀錄
台大學生女生總人數: 14086

# Q3.成大學生總人數

In [38]:
df12 = df[['總計','學校名稱']] # 取出想要觀看的欄位
print("本資料集共有", len(df12) , "筆紀錄")

df12_1 = df12[df12['學校名稱'] == '國立成功大學']

print("成大學生總人數:", df12_1['總計'].sum())

本資料集共有 764 筆紀錄
成大學生總人數: 23082